### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by benjaminwache** [fcocquemas/rdatastream#1]
Hey François, thanks for writing this library.
When i followed your basic instructions, R gave me an error when trying to make the first request (the IBM example):
"Error in apply(records, 2, function(record) { : 
  dim(X) must have a positive length"

What do you make of this?

**Comment by Jakobsjoerup** [comment]
Hi François,

As benjaminwache said, thank you for writing this library.
Could there be any other reasons for the error message above?
I'm using valid credentials, but I still cannot retrieve the data from Datastream.

Thanks in advance!

Sincerely, 
Jakob

**Comment by fcocquemas** [comment]
Hi Jakob,

Did you happen to add "DS:" in front of your usual username? If that still doesn't work, what was the request you were trying to send?

**Comment by Jakobsjoerup** [comment]
Hi again,

Thank you for getting back to me so fast.
I tried both with and without "DS:" in front of my usual username and none of the options work.
The request I tried to send was the usual (just to test it):

dat <- ds(user, securities = "U:IBM", fields = c("P","MV"), date = 2015-04-30)

I followed the instructions step by step, but I still get an error message..

**Comment by fcocquemas** [comment]
Hi Jakob,

Can you try with quotes around the date ("2015-04-30") ?

**Comment by Jakobsjoerup** [comment]
Sure. I just forgot to re-ad the quotes when I changed the date earlier. But I'm afraid it still doesn't work. 

When I ran through the earlier steps, I also got the message:

> library("RCurl")
Loading required package: bitops
Warning message:
package ‘RCurl’ was built under R version 3.5.2 

What do you think of that?

**Comment by Jakobsjoerup** [comment]
FYI, I'm using an e-mail address provided by my company as username. That is the one I usually login with. Can that be a problem?

**Comment by fcocquemas** [comment]
Yes, your login is almost definitely the problem. The login should be around 7 alphanumerical characters.

You can reinstall RCurl if you want but I doubt it would affect it.

**Comment by Jakobsjoerup** [comment]
Hmm, ok.. I think I'll try to contact Thomson Reuters (Refinitiv) and see if they can provide me with another login then. Thank you for your help!

**Comment by fcocquemas** [comment]
I don't have a Datastream Professional ID (which is your company email), just a regular Datastream ID, so I can't try this. But: you could try to HTML encode the "@" in your email and see if this works. You can use something like gsub("@", "&#64;", "name@company.com"). The Datastream requests use the "@" symbol for something else.

**Comment by Jakobsjoerup** [comment]
So if I understand you correctly, I should send something like:

user <- list(username = gsub("@","@","name@company.com") , password = "**********")

Where I - of course - replace "name@company.com" with my actual email and the password with my actual password.

Sorry in advance if i don't get this correctly, I'm not so experienced with R (coding in general) yet.

**Comment by fcocquemas** [comment]
Ugh, sorry, Github actually decoded the @ sign! Basically replace the `@` in your email with `&#64;` and see if that works. You don't need the gsub.

**Comment by Jakobsjoerup** [comment]
Hmm.. I'm afraid it still doesn't work. I keep getting the same error message no matter which of the options I try, i.e. with and without the prefix. Thank you so much for trying to help me, but I don't think I can be helped :D I'll contact Thomson Reuters tomorrow and see if they can get me an applicable username.

**Comment by fcocquemas** [comment]
Let me know if you figure it out!

**Comment by Jakobsjoerup** [comment]
I will!
