### ISSUE TITLE
Unable to make requests

### ISSUE THREAD

**Issue by Eshan-G** [fcocquemas/rdatastream#12]
Hi François, thanks for writing this library.

I am running into the same error as previous users here: https://github.com/fcocquemas/rdatastream/issues/1

I have tried all the advice you provided the link above regarding how to correctly specify the username but I still get the same error as other when making requests (including requests straight from the documentation e.g. `dat <- ds(user, requests = "U:IBM~=NAME,ISIN~REP")`):

This is the error:

```
Error in apply(records, 2, function(record) { :
dim(X) must have a positive length
```

Like a user in the previous issue post, I also have a company email as my username. I have used the username to log into Thomson Reuters Datastream and successfully make requests in the desktop app and the Excel add in.

Is there any way I can use my login credentials to make Datastream requests in R using your library?

Thanks

**Comment by fcocquemas** [comment]
Hi Eshan,

Unfortunately, it looks like the email login doesn't work with this API
(or, there's something we haven't figured out). I would reach out to
Thomson Reuters and ask them if there's another login you need to use.

Let me know how it goes

Best,
François

**Comment by Eshan-G** [comment]
Hi François,

Thanks for your response. 

I will contact Thomson Reuters in that case and let you how it goes.

Eshan

**Comment by Eshan-G** [comment]
Hi François,

The library now works.

I called Thomson Reuters and they provided my login credentials for 'Datastream for Office' (DFO) which are different to Thomson Reuters Eikon login credentials, the former being only alpha numeric and the latter an email login.

The DFO credentials work when trying to use the library.

Eshan

**Comment by fcocquemas** [comment]
Thanks for the update Eshan!
