### ISSUE TITLE
Requesting user defined expression

### ISSUE THREAD

**Issue by abbanerjeersm** [fcocquemas/rdatastream#2]
Hi,

I was wondering if this API is capable of retrieving a user defined expression in Datastream instead of system defined expressions like MAV#. 

Not sure if opening up an issue is the right way to request for clarification - as I am new to Git.

**Comment by fcocquemas** [comment]
Would you happen to have a reference link for the type of user-defined expressions you mean? I'm not familiar with them.

If it's something you've saved in Excel or another interface, I doubt it's possible to retrieve them through the API.

**Comment by abbanerjeersm** [comment]
Hi,

I got some help from Datastream DWI API team to understand how this request needs to be formulated. For example if you have a user defined function that you have developed, you can use it in the following format.

E237(U:IBM)~2010-01-01~:2015-01-01~D~#<username>

Here E237 is a user defined function that I have defined and is accesible via my user id. I think its useful to have this example in the readme file for others to refer to.

**Comment by fcocquemas** [comment]
Thank you, added the example to the Readme!
