### ISSUE TITLE
HTML encode tickers

### ISSUE THREAD

**Issue by fcocquemas** [fcocquemas/rdatastream#3]
Package should encode HTML entities in tickers before sending the XML request. For instance, the S&P tickers, `"S&PCOMP"`, doesn't work as expected. Right now, the workaround is to do the encoding manually (`"S&amp;PCOMP"`), or you can use `htmltools::htmlEscape`.

```
htmltools::htmlEscape("S&PCOMP")
# [1] "S&amp;PCOMP"
```

I'll make the appropriate changes is the code soon.

**Comment by ucb** [comment]
I have learned this problem the hard way. A number of identifiers have to be enclosed in `"<>"` which throws an error. `"&lt;............&gt;"` works inside of requests.

It took me several angry emails to TR team to finally come up with the solutions ;)

**Comment by fcocquemas** [comment]
Thanks for the comment, that's good to know. Would you have an example of such a ticker for when I update the package/README?

**Comment by ucb** [comment]
Hi François,


.dMIWO0ME00GUS


I am not sure if that is limited to all indices or to all RICs (it is a RIC for an index).


E.g.

data.table(ds(user, requests = "&lt;.dMIWO0ME00GUS&gt;(RI)~~NOK~1979-12-31~:2017-03-31~M")[[7]]) )

works, but

data.table(ds(user, requests = ".dMIWO0ME00GUS(RI)~~NOK~1979-12-31~:2017-03-31~M")[[7]]) )

does not (also does not work with explicit <>).


Cheers,

Barbara


________________________________

**Comment by fcocquemas** [comment]
Oh, gotcha! Thank you. Good to know RICs work, I had never tried.
