### ISSUE TITLE
Username deprecated

### ISSUE THREAD

**Issue by WillBtK** [fcocquemas/rdatastream#4]
Using the guidelines on installation, the command:
install_github("RDataStream", username="fcocquemas")
returns the error:

> Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
>   Timeout was reached
> In addition: Warning message:
> Username parameter is deprecated. Please use fcocquemas/RDataStream

Using the indicated username becomes recursive, adding on subsequent /RDataStream recommendations.

**Comment by fcocquemas** [comment]
You should now use `install_github("fcocquemas/RDataStream")`, I've updated the instructions.
