### ISSUE TITLE
Server connection issue

### ISSUE THREAD

**Issue by WillBtK** [fcocquemas/rdatastream#5]
When installing using install_github("fcocquemas/RDataStream"), I get the error:

> Error in curl::curl_fetch_disk(url, x$path, handle = handle) : Couldn't connect to server

I'm connecting from inside a company network.

**Comment by fcocquemas** [comment]
This is likely a problem with your company firewall, not with the package.

You can try the following:
- Go to the [main project page](https://github.com/fcocquemas/rdatastream)
- Click the "Clone or download" button
- Download zip, and unzip
- In R, do `install.packages(path_to_dir, repos = NULL)`, replacing `path_to_dir` with the path to the directory where you unzipped the file

Of course, this will only work if the dependencies are installed.

**Comment by WillBtK** [comment]
Thanks Francois,Sorry to be a little slow on the uptake here, as it's my first time trying to install from anywhere other than CRAN, so my apologies if my questions are rather naive.
Is there a subfolder to which I should be pointing? For example, if I point to RDataStream, RDataStream/rdatastream-master, or similar, I get the error:Error in install.packages : type = "both" cannot be used with 'repos = NULL'
I've also changed my working directory to various permutations of the subfolders and again without any success.
Thank you again, and apologies for the questions!Will



		_____________________________

**Comment by fcocquemas** [comment]
Do you mean for the `path_to_dir` in my instructions? This is supposed to be the path to `rdatastream-master` on your local hard drive.

You can also try this, if your proxy lets you:

    tmpfile <- tempfile()
    download.file("https://github.com/fcocquemas/rdatastream/archive/master.zip", tmpfile)
    tmpdir <- tempfile()
    unzip(tmpfile, exdir = tmpdir)
    install.packages(file.path(tmpdir, "rdatastream-master"), repos=NULL)

**Comment by WillBtK** [comment]
Thanks Francois. I initially ran into the same problem, then realised that, in the install.packages line, I need to add type="source".
Thanks again for your help, and I look forward to trying it out! If it is released on CRAN, I'd love to know.
Thanks,Will



		_____________________________

**Comment by fcocquemas** [comment]
Glad it works. 

I'm actually hoping to modernize the interface a bit at some point, then maybe I'll submit to CRAN.
