### ISSUE TITLE
Cannot retrieve more than 18 variables at once?

### ISSUE THREAD

**Issue by LeuteMatthias** [fcocquemas/rdatastream#7]
Hello again François,
I have yet another issue and I hope you would help me out one more time.

When I try to retrieve more than 18 variables at a time, I found it necessary to `cbind` data frames because every variable after the 18th is skipped although I can still find them still in the "Instruments" list. The "Fields" list indicates the same number of fields though no matter how many variables I choose. Maybe I am also doing something wrong?
Importantly, I would like to avoid the `cbind` function as it takes lots of time and produces errors when the first variable is not available for a certain firm because there is no data frame created by the ds function in that case. If the variable is not the first one to retrieve the ds function skips the variable, which is fine for me.

A small example below:

````
Firm <- c("952472")
Variables_18 <- c("SOEQDP025","SOEQDP028","SOEQDP035","SOEQDP036","SOEQDP037","SOHSDP0011","SOHSDP0013","SOHSDP0031","SOHSDP0033","SOHSDP004","SOHSDP0071","SOHSDP0073","SOHSDP0081","SOHSDP0083","SOHSDP011","SOHSDP0121","SOHSDP0123","SOHSDP013")
Variables_18_plus <- c("SOEQDP025","SOEQDP028","SOEQDP035","SOEQDP036","SOEQDP037","SOHSDP0011","SOHSDP0013","SOHSDP0031","SOHSDP0033","SOHSDP004","SOHSDP0071","SOHSDP0073","SOHSDP0081","SOHSDP0083","SOHSDP011","SOHSDP0121","SOHSDP0123","SOHSDP013","SOHSDP014","SOHSDP0161","SOHSDP0163","SOHSDP0181")

ds(user, securities = Firm, fields = Variables_17, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y")
ds(user, securities = Firm, fields = Variables_17, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y")["Data",1][[1]]

ds(user, securities = Firm, fields = Variables_17_plus, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y")
ds(user, securities = Firm, fields = Variables_17_plus, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y")["Data",1][[1]]
```

**Comment by fcocquemas** [comment]
Hello Matthias,

I don't seem to have access to the data you are trying to fetch, so I couldn't test your exact example. Here is what I tried instead:

```
fields <- c("AF", "CAI", "DY", "EPS", "MV", "MVC", "MVFF", "PL", 
  "PO", "P", "PI", "PA", "PB", "RI", "VO", "UP", "PTBV", "PC", "APC")
length(fields) # 19
dt <- ds(user, securities = "@MSFT", fields = fields, fromDate = "2002-12-31", 
  toDate = "2015-12-31", period = "Y")
dt["Data",1][[1]]
```

It does seem like you are right – although the request appears to be well understood by the server, it does not return anything for the 19th variable and beyond.

For now, I think it's better to let the user handle this case (maybe throwing a warning). 

Note that you can send several requests in one API call. For instance:

```
dt <- ds(user,
  requests=c(
    "@MSFT~=AF,CAI,DY,EPS,MV,MVC,MVFF,PL,PO,P,PI,PA,PB,RI,VO,UP,PTBV,PC~2002-12-31~:2015-12-31~Y", 
    "@MSFT~=APC~2002-12-31~:2015-12-31~Y"))
```

I hope this helps,
François

**Comment by LeuteMatthias** [comment]
Ok, thanks for the quick response once again!
I looped it for now, which works all right. Just takes more time.

Thanks,
Matt

**Comment by fcocquemas** [comment]
No problem! Thanks for the report.
François
