### ISSUE TITLE
Running out of Memory

### ISSUE THREAD

**Issue by kn1g** [fcocquemas/rdatastream#9]
Hi,

my code crashes and I can not figure out why this happens, because the XML request are managed within the rdatastream package. The whole system crashes with out of Stringbuffer errors and R shows this error:

```
Memory allocation failed : building node

xmlSAX2StartElementNsExtra content at the end of the document

xmlSAX2CharactersMemory allocation failed : growing buffer

Memory allocation failed : growing buffer
```

My code basically builds up a query string and put this in the ds() function (see line 104 to 115 in https://github.com/kn1g/ReutersAPI-ShinyApp/blob/master/makeAssetObject.R ). It works well for some hours. But after maybe 4 hours the whole process crashes. 

My PC has 64GB Ram. I do not think there is a problem with the overall RAM. 

Could it be that there is any kind of limit with the XML requests or a variable that keeps growing?
I am not even sure if my code or your code produces the error. But because I am not dealing with the XML request and the error is XML related, I think it's the rdatastream package.

Best,
Nico

**Comment by kn1g** [comment]
Ok, I am reading through your code at the moment. There is one thing I noticed. I used the ds() function without specifing the requests argument specifically. But it worked anyway... So, I don't know if this causes trouble.

**Comment by fcocquemas** [comment]
Nico,

1/ Could you maybe track memory usage over time to see if indeed there is some sort of leak? `pryr::mem_used()` should help you see if the memory used consistently grows over time.
2/ Does the problem occurs consistently after four hours? Any chance you could save the raw output from the DS requests to a file, in order to examine which request caused the error? It might be the DS servers sending problematic XML (the parsing of which would depend of package `XML`).

Hope this helps!
F

**Comment by kn1g** [comment]
Ok, I'll try to track the mem usage. The problem is the whole RSession crashes. Which makes any kind of debugging hard. I will write the mem usage into a logfile. But that's a good idea. I do not have a lot of experience with memory problems.

The problem occured the second time. I'm requesting ~50 assets per request. The full asset list is around 20'000 assets. So it runs for quite a while. I sometimes also use two accounts in parallel in two RSessions. I save parts of the outputs and all errors. So also what the error msg from the ds() requests. I run three sessions parallel with different accounts. They crashed with these kind of error msgs:

```
Error: 1: Memory allocation failed : building node2: xmlSAX2StartElementNs3: Extra content at the end of the document

Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE, : arguments imply differing number of rows: 11654, 4228
```

Apparently the other session crashed with these errors:

```
Error in grepl(\\\\u[0-9A-Fa-f], str): could not allocate memory (63 Mb) in C function 'R_AllocStringBuffer

Error in paste(txt, collapse = collapse): could not allocate memory (34 Mb) in C function 'R_AllocStringBuffer

Error in paste(txt, collapse = collapse): could not allocate memory (22 Mb) in C function 'R_AllocStringBuffer

Error: cannot allocate vector of size 35.0 Mb
```

**Comment by fcocquemas** [comment]
Closed as this does not appear to be a RDatastream issue.
